version: 0.1.0.{build}
image: Visual Studio 2017
init:
- ps: >-
    $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER.PadLeft(4, "0")

    git config --global core.autocrlf true
before_build:
- ps: >-
    appveyor-retry dotnet restore -v Minimal

    .\ModifyVersion.ps1 $env:APPVEYOR_BUILD_FOLDER\NetIRC\NetIRC.csproj $env:APPVEYOR_BUILD_NUMBER
build:
  project: NetIRC.sln
  verbosity: minimal
before_package:
- cmd:
after_build:
- ps: dotnet pack "NetIRC" --no-build --version-suffix %LABEL% -o artifacts
test_script:
- ps: dotnet test NetIRC.Tests\NetIRC.Tests.csproj
artifacts:
- path: NetIRC\artifacts\*.*
  name: path
