version: 0.1.0.{build}
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    git config --global core.autocrlf true
before_build:
- ps: >-
    appveyor-retry dotnet restore -v Minimal

    .\ModifyVersion.ps1 $env:APPVEYOR_BUILD_FOLDER\src\NetIRC\NetIRC.csproj $env:APPVEYOR_BUILD_NUMBER
build:
  project: NetIRC.sln
  verbosity: minimal
after_build:
- ps: dotnet pack "src\NetIRC" --no-build -o artifacts
test_script:
- ps: dotnet test tests\NetIRC.Tests\NetIRC.Tests.csproj
after_test:
- nuget restore tests\CodeCoverage -PackagesDirectory tests\CodeCoverage
- tests\CodeCoverage\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test tests\NetIRC.Tests\NetIRC.Tests.csproj --no-build -c release" -hideskipped:All -oldStyle -output:.\NetIRC_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "NetIRC_coverage.xml"
artifacts:
- path: src\NetIRC\artifacts\*.*
  name: path
