version: 0.1.0.{build}
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    git config --global core.autocrlf true
before_build:
- ps: >-
    appveyor-retry dotnet restore -v Minimal

    .\ModifyVersion.ps1 $env:APPVEYOR_BUILD_FOLDER\src\NetIRC\NetIRC.csproj $env:APPVEYOR_BUILD_NUMBER
build:
  project: NetIRC.sln
  verbosity: minimal
after_build:
- ps: dotnet pack "src\NetIRC" --no-build -o artifacts
test_script:
- ps: dotnet test tests\NetIRC.Tests\NetIRC.Tests.csproj
artifacts:
- path: src\NetIRC\artifacts\*.*
  name: path
